name : ps-exact
channels:
  - legate/label/experimental
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - jax
  - matplotlib
  - notebook
  - tqdm=4.67.1
  - threadpoolctl=3.6.0
  - line_profiler
  - cupy
  - nvtx
  - cupynumeric
  - pytorch-cuda
  - pytorch
  - torchvision
