name : ps-exact
channels:
  - legate/label/experimental 
#  - legate/label/rc
  - pytorch
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - jax
  - matplotlib
  - notebook
  - tqdm=4.67.1
  - threadpoolctl=3.6.0
  - line_profiler
  - cupy
  - nvtx
#  - cupynumeric=25.05.00.rc3
  - cupynumeric
  - pytorch-cuda
  - pytorch
  - torchvision
