name: ps-exact-gh
channels:
  - legate/label/experimental
  - conda-forge
dependencies:
  - python=3.12
  - cupynumeric
  - numpy
  - jax
  - opt_einsum
  - matplotlib
  - notebook
  - tqdm=4.67.1
  - threadpoolctl=3.6.0
  - line_profiler
  - h5py
  - pip
  - pip:
      - cupy-cuda12x
      - nvtx
      - torch
      - torchvision
