name : test_yml
channels: 
  - legate/label/rc
  - conda-forge
dependencies:
  - python=3.12
  - pyscf
  - numpy
  - jax
  - matplotlib
  - notebook
  - tqdm=4.67.1
  - threadpoolctl=3.6.0
  - line_profiler
  - cupy
  - cupynumeric=25.05.00.rc3
