[project]
name = "exact-grid-quantum"
version = "0.1.0"
requires-python = ">=3.12, <3.13"
dependencies = [
    "pyscf",
    "numpy",
    "jax",
    "matplotlib",
    "notebook"  # For running Jupyter notebooks
]

[tool.setuptools.packages.find]
where = ["lib"]