#!/usr/bin/env python
# Copyright 2014-2020 The PySCF Developers. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Author: Qiming Sun <osirpt.sun@gmail.com>
#

#
# Heavily modified by Vale Cofer-Shabica <vale.cofershabica@gmail.com>, 2025
#
# Copy of linalg_helper.py with root locking/deflation added to davidson1
# (Saad, "Numerical Methods for Large Eigenvalue Problems", 2nd ed., Sec.
# 5.3.1 "Locking"): once a root's eigenvalue has stopped moving and its
# residual is within `lock_tol_factor` of the target, it is frozen out of
# the active working set instead of being rebuilt from scratch on every
# max_space restart.
#

import xp
import numpy  # only for *scalar* math
import gc
from sys import stdout
import logger

from debug import timer, timer_ctx
from time import perf_counter


def _free_cupy_memory_pool():
    if xp.backend != 'cupy':
        return
    import cupy
    cupy.cuda.Stream.null.synchronize()
    cupy.get_default_memory_pool().free_all_blocks()
    cupy.get_default_pinned_memory_pool().free_all_blocks()
    gc.collect()


def davidson1(aop, x0, precond, tol=1e-12, max_cycle=50, max_space=100,
              max_trial=40,
              lindep=1e-14, max_memory=8000,
              callback=None,
              nroots=1, verbose=logger.WARN,
              tol_residual=None,
              lock=False, lock_tol_factor=10.,
              ):
    r"""Davidson diagonalization method to solve  a c = e c.  Ref
    [1] E.R. Davidson, J. Comput. Phys. 17 (1), 87-94 (1975).
    [2] http://people.inf.ethz.ch/arbenz/ewp/Lnotes/chapter11.pdf

    Note: This function has an overhead of memory usage ~4*x0.size*nroots

    Args:
        aop : function([x]) => [array_like_x]
            Matrix vector multiplication :math:`y_{ki} = \sum_{j}a_{ij}*x_{jk}`.
        x0 : 1D array or a list of 1D arrays or a function to generate x0 array(s)
            Initial guess.  The initial guess vector(s) are just used as the
            initial subspace bases.  If the subspace is smaller than "nroots",
            eg 10 roots and one initial guess, all eigenvectors are chosen as
            the eigenvectors during the iterations.  The first iteration has
            one eigenvector, the next iteration has two, the third iteration
            has 4, ..., until the subspace size > nroots.
        precond : diagonal elements of the matrix or  function(dx, e, x0) => array_like_dx
            Preconditioner to generate new trial vector.
            The argument dx is a residual vector ``a*x0-e*x0``; e is the current
            eigenvalue; x0 is the current eigenvector.

    Kwargs:
        tol : float
            Convergence tolerance.
        max_cycle : int
            max number of iterations.
        max_space : int
            space size to hold trial vectors.
        max_trial : int
            maximum trial vectors to work with at a time; only matters if max_trial < nroots
        lindep : float
            Linear dependency threshold.  The function is terminated when the
            smallest eigenvalue of the metric of the trial vectors is lower
            than this threshold.
        max_memory : int or float
            Allowed memory in MB.
        callback : function(envs_dict) => None
            callback function takes one dict as the argument which is
            generated by the builtin function :func:`locals`, so that the
            callback function can access all local variables in the current
            environment.
        nroots : int
            Number of eigenvalues to be computed.  When nroots > 1, it affects
            the shape of the return value
        lock : bool
            Enable root locking/deflation. When a root's eigenvalue has
            converged (``|de| < tol``) and its residual norm has dropped to
            within ``lock_tol_factor`` of ``tol_residual``, it is frozen:
            excluded from further correction-vector generation *and* carried
            as a fixed row/column of the subspace across ``max_space``
            restarts instead of being discarded and rebuilt from scratch.
            This targets the common Davidson pathology where the Ritz value
            stabilizes long before the Ritz vector (residual) does -- without
            locking, every restart re-spends effort reconverging roots that
            were already good enough. Locked roots are reported as converged
            at the looser ``lock_tol_factor * tol_residual`` bound rather
            than the full ``tol_residual``. Default False (identical to the
            unlocked algorithm).
        lock_tol_factor : float
            How much looser than ``tol_residual`` a root's residual may be
            before it gets locked. Default 10.

    Returns:
        conv : bool
            Converged or not
        e : list of floats
            The lowest :attr:`nroots` eigenvalues.
        c : list of 1D arrays
            The lowest :attr:`nroots` eigenvectors.

    Examples:

    >>> from pyscf import lib
    >>> a = xp.random.random((10,10))
    >>> a = a + a.T
    >>> aop = lambda xs: [xp.dot(a,x) for x in xs]
    >>> precond = lambda dx, e, x0: dx/(a.diagonal()-e)
    >>> x0 = a[0]
    >>> e, c = lib.davidson(aop, x0, precond, nroots=2)
    >>> len(e)
    2
    """
    _tic("start")
    if isinstance(verbose, logger.Logger):
        log = verbose
    else:
        log = logger.Logger(stdout, verbose)

    if tol_residual is None:
        tol_residual = numpy.sqrt(tol)
    lock_tol_residual = lock_tol_factor * tol_residual

    log.debug1('tol %g  tol_residual %g  lock %s  lock_tol_residual %g',
                tol, tol_residual, lock, lock_tol_residual)

    if not callable(precond):
        precond = make_diag_precond(precond)

    x0 = xp.atleast_2d(x0)
    Nelem = xp.size(x0[0])

    max_cycle = min(max_cycle, Nelem)
    max_space = max_space + (nroots-1) * 4
    # max_space*2 for holding ax and xs, nroots*2 for holding axt and xt
    required_memory = (max_space*2 + nroots*3) * x0[0].nbytes / 1024 / 1024
    allow_resize = False
    if  required_memory > max_memory:
        log.warn("Required space is %d MB, but max memory is %d MB. "
                 "Resizing will be allowed, but the performance penalty may be significant.", required_memory, max_memory)
        allow_resize = True
    log.debug1("max_cycle %d  max_space %d  Nelem %d  required_memory %dMB  max_memory %dMB  resize %s",
               max_cycle, max_space, Nelem, required_memory, max_memory, allow_resize)

    # FIXME: aop(x0) is a wasted calculation.  On CuPy this probe can also
    # leave a large contraction workspace in the memory pool, so release it
    # before allocating the Davidson xs/ax basis.
    ax0_probe = aop(x0[:1])
    dtype = xp.result_type(ax0_probe, x0)
    del ax0_probe
    _free_cupy_memory_pool()
    log.debug("dtype=%s", dtype)

    if not allow_resize:
        xs = xp.empty((max_space, Nelem), dtype=dtype)
        ax = xp.empty((max_space, Nelem), dtype=dtype)

    fresh_start = True
    heff = xp.zeros((max_space,max_space), dtype=dtype)
    e = None
    v = None
    conv = xp.zeros(nroots, dtype=bool)
    locked = xp.zeros(nroots, dtype=bool)
    nlocked = 0
    ax0_full = None
    emin = None

    _tic("init")
    for icyc in range(max_cycle):
        _tic("cycle")
        if fresh_start:
            if allow_resize:
                xs = xp.empty((0, Nelem), dtype=dtype)
                ax = xp.empty((0, Nelem), dtype=dtype)

            space = 0

            if lock and nlocked > 0:
                # Re-seed the frozen roots as fixed rows of the fresh
                # subspace. Their matvecs are already known exactly --
                # A(Vv) = (AV)v for linear A -- so no extra aop() calls are
                # spent reconverging something that already converged.
                locked_xs = x0[locked]
                locked_ax = ax0_full[locked]
                if allow_resize:
                    xs = xp.concatenate((xs, locked_xs))
                    ax = xp.concatenate((ax, locked_ax))
                else:
                    xs[:nlocked] = locked_xs
                    ax[:nlocked] = locked_ax
                space = nlocked
                # heff is a persistent buffer that is *not* zeroed on
                # restart -- its [:nlocked, :nlocked] corner still holds
                # stale entries from the previous restart cycle's much
                # larger subspace. Rebuild that corner from the locked
                # vectors themselves (row0=0 so this fills the diagonal
                # block only, no coupling to fill yet).
                _fill_heff_hermitian(heff, ax[:nlocked], locked_xs, locked_ax)
                active0 = x0[~locked]
            else:
                active0 = x0

            xt = _qr(active0)

            if len(xt) != len(active0):
                log.warn('QR decomposition removed %d vectors.', len(active0) - len(xt))
                if len(xt) == 0:
                    if icyc == 0:
                        msg = 'Initial guess is empty or zero'
                    else:
                        msg = ('No more linearly independent basis were found. '
                               'Unless loosen the lindep tolerance (current value '
                               f'{lindep}), the diagonalization solver is not able '
                               'to find eigenvectors.')
                    raise RuntimeError(msg)
            _tic("fresh_start")
        elif len(xt) > 1:
            xt = _qr(xt)[:max_trial]
            _tic("qr")

        axt = aop(xt)

        if allow_resize:
            xs = xp.concatenate((xs, xt))
            ax = xp.concatenate((ax, axt))
        else:
            nxt = len(xt)
            xs[space:space+nxt] = xt
            ax[space:space+nxt] = axt
        space += len(xt)

        elast = e
        vlast = v
        conv_last = conv
        locked_last = locked

        _fill_heff_hermitian(heff, ax[:space], xt, axt)
        _tic("heff")

        e, v = xp.linalg.eigh(heff[:space,:space])
        e = e[:nroots]
        v = v[:,:nroots]
        _tic("diag heff")

        if not fresh_start:
            elast, conv_last, locked = _sort_elast(elast, conv_last, locked_last, vlast, v, log)
        else:
            locked = locked_last

        if elast is None:
            de = e
        elif xp.size(e) != xp.size(elast):
            log.debug('Number of roots different from the previous step (%d,%d)',
                      xp._size(e), xp._size(elast))
            de = e
        else:
            de = e - elast
        _tic("bookkeeping")

        x0 = _from_subspace(v, xs[:space])
        ax0_full = _from_subspace(v, ax[:space])
        xt = ax0_full - e[:,None]*x0
        dx_norm = xp.linalg.norm(xt, axis=1)
        conv = (xp.abs(de) < tol) & (dx_norm < tol_residual)

        if lock:
            newly_locked = ~locked & (xp.abs(de) < tol) & (dx_norm < lock_tol_residual)
            if xp.any(newly_locked):
                locked = locked | newly_locked
                for k in xp.where(newly_locked)[0]:
                    k = int(k)
                    log.debug('root %d locked  |r|=%4.3g  e=%s  max|de|=%4.3g',
                              k, float(dx_norm[k]), float(e[k]), float(de[k]))
            conv = conv | locked
        # Recompute unconditionally (not just when newly_locked fires): a
        # root can also get silently *un*locked by the _sort_elast remap
        # above if its overlap with the previous cycle was ambiguous
        # (found=False), and nlocked must stay in sync with `locked` for
        # the fresh_start seeding logic to be consistent.
        nlocked = int(xp.sum(locked))
        _tic("outer")

        for k, ek in enumerate(e):
            if conv[k] and not conv_last[k]:
                log.debug('root %d converged  |r|=%4.3g  e=%s  max|de|=%4.3g',
                          k, dx_norm[k], ek, de[k])

        ide = xp.argmax(abs(de))

        if all(conv):
            log.info('converged %d %d  |r|=%4.3g  e=%s  max|de|=%4.3g',
                      icyc, space, dx_norm.max(), e, de[ide])
            break

        # remove subspace linear dependencies (locked roots are already
        # excluded here since conv[locked] is forced True above)
        keep = ~conv & (dx_norm > numpy.sqrt(lindep))
        xt = xt[keep]

        if len(xt) == 0:
            log.debug('Linear dependency in trial subspace. |r| for each state %s',
                      dx_norm)
            conv = dx_norm < tol_residual
            if lock:
                conv = conv | locked
            break
        _tic("lindep")

        # N.B. If we use the jitted preconditioner, this takes longer the first time through
        #xt = xp.asarray([precond(xt_, e[0], x0_) for xt_, x0_ in zip(xt, x0[keep])])

        # With a properly batched preconditioner, and when under jax,
        # we get major stalls after converging an eigenpair. why?

        xt = precond(xt, e[0], x0[keep])
        _tic("precond")
        norms = xp.linalg.norm(xt, axis=1)
        xt /= norms[:, None]

        xt, norm_min = _orthonormalize_xt(xt, xs[:space], lindep)
        log.debug('davidson %d %d  |r|=%4.3g  e=%s  max|de|=%4.3g  lindep=%4.3g  locked=%d',
                  icyc, space, dx_norm.max(), e, de[ide], norm_min, nlocked)

        if icyc > 3 and de[0] > 0 and abs(de[0]) > tol:
            log.debug("Hold up! Why isn't de monotonic??? %s", de)

        # Only the still-active roots need to fit under max_space on the
        # next cycle -- locked roots are re-seeded for free on restart and
        # never contribute a new trial vector (see the `keep` mask above).
        n_active = nroots - nlocked
        fresh_start = space+n_active > max_space

        # useful, e.g., for restarts
        if callable(callback):
            callback(locals())

    foundroots, _ = x0.shape
    if foundroots < nroots:
        # Two possible reasons:
        # 1. All the initial guess are the eigenvectors. No more trial vectors
        # can be generated.
        # 2. The initial guess sits in the subspace which is smaller than the
        # required number of roots.
        log.warn(f'Not enough eigenvectors (len(x0)={len(x0)}, nroots={nroots})')

    return conv, e, x0


def make_diag_precond(diag, level_shift=1e-3):
    """Generate the preconditioner function with the diagonal function."""
    # For diagonal matrix A, precond (Ax-x*e)/(diag(A)-e) is not able to
    # generate linearly independent basis (see PySCF issue 1362). Use level_shift to
    # break the correlation between Ax-x*e and diag(A)-e.
    # FIXME: need to make sure this is batched too
    def precond(dx, e, *args):
        diagd = diag - (e - level_shift)
        diagd[abs(diagd)<1e-8] = 1e-8
        return dx/diagd
    return precond


def _qr(X):
    return (xp.linalg.qr(X.T)[0]).T


def _from_subspace(v, xs):
    v = xp.atleast_2d(v)
    # CuPy's einsum path for 'ik,ij->kj' can materialize a huge contiguous
    # copy of xs.T at large Davidson spaces.  The explicit matmul keeps the
    # large basis in its native (space, Nelem) layout; only v.T is tiny.
    return xp.ascontiguousarray(v.T) @ xs


def _sort_elast(elast, conv_last, locked_last, vlast, v, log):
    """
    Eigenstates may be flipped during the Davidson iterations.  Reorder the
    eigenvalues of last iteration (and any other per-root bookkeeping array
    keyed the same way, e.g. the locked mask) to make them comparable to the
    eigenvalues of the current iterations.
    """
    head, nroots = vlast.shape
    ovlp = xp.abs(xp.einsum('ij,jk->ik', v[:head].conj().T, vlast))
    mapping = xp.argmax(ovlp, axis=1)
    found = xp.any(ovlp > .5, axis=1)

    if log.verbose >= logger.DEBUG:
        ordering_diff = (mapping != xp.arange(len(mapping)))
        if any(ordering_diff & found):
            log.debug('Old state -> New state')
            for i in xp.where(ordering_diff)[0]:
                log.debug('  %3d     ->   %3d ', mapping[i], i)

    conv = conv_last[mapping]
    locked = locked_last[mapping]
    e = elast[mapping]
    conv[~found] = False
    locked[~found] = False
    e[~found] = 0.
    return e, conv, locked


def _orthonormalize_xt(xt, xs, threshold):
    """Projects out existing basis vectors xs. Also checks whether the precond
    function is ill-conditioned"""

    # Project: xt_mat -= xs.T @ (xs @ xt_mat.T)
    # In detail: subtract each xi's projection onto the span of xs
    proj = xs.conj() @ xt.T     # shape: (nbasis, nvecs)
    xt -= (proj.T @ xs)  # shape: (nvecs, ndim)

    # Compute norms
    norms = xp.linalg.norm(xt, axis=1)
    keep = norms**2 > threshold

    # Normalize and select
    xt = xt[keep]
    norms = norms[keep]
    if xt.size == 0:
        return [], 1
    xt /= norms[:, None]

    return xt, norms.min()


def _fill_heff_hermitian(heff, ax, xt, axt):
    # Stack active blocks
    nrow = len(axt)
    row1 = len(ax)
    row0 = row1 - nrow

    # === Block A: lower-right (nrow x nrow), symmetric ===
    block_A = xt.conj() @ axt.T  # shape (nrow, nrow)
    heff[row0:row1, row0:row1] = (block_A + block_A.T.conj()) / 2

    if row0 > 0: # cupynumeric requires this test
        # === Block B: off-diagonal (row0 x nrow), symmetric ===
        block_B = xt.conj() @ ax[:row0].T  # shape (nrow, row0)
        heff[row0:row1, :row0] = block_B
        heff[:row0, row0:row1] = block_B.T.conj()

    return heff

__lasttime = None
def _tic(label):
    global __lasttime
    printing = False
    if printing and __lasttime:
        print(f"EEElapsed {label}", perf_counter() - __lasttime)
    __lasttime = perf_counter()
